### PR TITLE
Aco prefix tree

### PR DESCRIPTION
**Pull request by golgher**
Update AclExtras and AclExtrasTest to generate ACOs based on App's Routes

### CODE REVIEW

**Comment by markstory** [comment]
If the routes change, won't the aco tree be invalid?

**Comment by golgher** [comment]
You're right, probably if we filter the routes to use only App default route, Plugins default route and all prefixes this code will work, because these three cases define the ACO path template, what do you think?

**Comment by golgher** [comment]
This AclExtras have the same logic of the current, but instead of do this:
```php
$this->_processControllers($root);
$this->_processPrefixes($root);
$this->_processPlugins($root, $plugins);
```
I get all the necessary routes (app default route, plugins default routes and all prefixes) and based on this routes will be generate ACOs for controllers and action.

Another change, after I analyse the code of ActionsAuthorize.php and BaseAuthorize.php, I have concluded that the ACO path always will be checked using this template: /:plugin/:prefix/:controller/:action, so ACOs tree must be generated using the same template.

ActionsAuthorize.php:
```php
return $Acl->check($user, $this->action($request));
```
BaseAuthorize.php:
```php
 public function action(Request $request, $path = '/:plugin/:prefix/:controller/:action')
    {
        $plugin = empty($request['plugin']) ? null : preg_replace('/\//', '\\', Inflector::camelize($request['plugin'])) . '/';
        $prefix = empty($request['prefix']) ? null : $request['prefix'] . '/';
        $path = str_replace(
            [':controller', ':action', ':plugin/', ':prefix/'],
            [Inflector::camelize($request['controller']), $request['action'], $plugin, $prefix],
            $this->_config['actionPath'] . $path
        );
        $path = str_replace('//', '/', $path);
        return trim($path, '/');
    }
```

**Comment by rchavik** [comment]
I did some testing and the results seem to be ok.

But I need more time to digests/understand the changes as this is built on top of several PRs.

**Comment by rchavik** [comment]
FYI,

I've a tree containing merged stuff from all three PRs in my laptop, but it's in the shop.

Please defer reviews for now.

**Comment by dakota** [comment]
Any more movement on this?

**Comment by rchavik** [comment]
Not yet. Sorry.

**Pull request closed without merging**
