### PR TITLE
Save the alias field

### PR DESCRIPTION
**Pull request by alexsmonte**

### CODE REVIEW

**Comment by alexsmonte** [comment]
When did any change was not saved the alias field in the table aros

**Comment by markstory** [comment]
When/how does the alias change?

**Comment by rchavik** [comment]
No, I don't think we should do this. Plugin consumers might want to use a different value for the alias.

For example, In Croogo, this behavior is attached to `User` and `Role` model. They update their own alias, and each with its own convention: `User-<username>` and `Role-{alias}`.  Both `User.username`
and `Role.alias` are not the model's displayField.

Furthermore, the plugin have never saved the `alias` field here. Even when it was in 2.x: https://github.com/cakephp/cakephp/blob/2.8/lib/Cake/Model/Behavior/AclBehavior.php#L111-L115

**Comment by alexsmonte** [comment]
Thinking this way really may not be good to do this, but the afterSave method could not be overridden?

**Comment by dakota** [comment]
@alexsmonte I think the solution here would be to call a `aclAlias()` (or similar) method in the entity. If the method does not exist then carry on as currently, but if it does, use the return value as the alias.

**Comment by dakota** [comment]
Going to mark this as closed due to inactivity.

**Comment by alexsmonte** [comment]
@dakota We could then 'alias' => isset ($ parent-> alias)? $ Parent-> alias: null

Is it possible to do so?

**Pull request closed without merging**
