### PR TITLE
Upgrade cakephp #132

### PR DESCRIPTION
**Pull request by rochamarcelo**

### CODE REVIEW

**Comment by saeideng** [comment]
`cakephp/cakephp3.5.0` requires php +5.6

**Comment by rochamarcelo** [comment]
@saeideng the idea is to keep php 5.5 as minimum version required?

**Comment by saeideng** [comment]
min 5.6 and removing php 5.6 from travis 
see https://travis-ci.org/cakephp/acl/builds/318754475

**Comment by rchavik** [comment]
Thanks,

I'll fix this up in a minute.

In the future, please learn about rebasing your local topic branch against upstream.

**Comment by rchavik** [comment]
Rebased and merged.

Thanks again.

**Pull request closed without merging**
