### PR TITLE
Fix error / warning in PHP 7.3

### LINKED ISSUE #149: Warning in PermissionsTable with php 7.3
PHP 7.3 complains about the "continue" in PermissionsTable line 144:
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

I guess the "continue" is intended to continue with the foreach loop and thus could be replaced by break and make all version of PHP happy.

### PR DESCRIPTION
**Pull request by chtheis**
fixes #149

### CODE REVIEW

**Comment by garas** [comment]
Add 7.3 to `.travis.yml` file

**Comment by garas** [comment]
You should add 7.3 version to https://github.com/cakephp/acl/blob/master/.travis.yml so your changes are tested against PHP 7.3 too. It would help find possible other 7.3 incompatibilities now and in the future changes.

Unfortunately tests [fails](https://travis-ci.org/cakephp/acl/builds/468186115) because CakePHP 3.7 deprecations, so somebody needs to fix that in another PR.

**Comment by chtheis** [comment]
Am 15.12.2018 um 12:38 schrieb Edgaras Janušauskas:
> You should add 7.3 version to 
> https://github.com/cakephp/acl/blob/master/.travis.yml so your changes 
> are tested against PHP 7.3 too. It would help find possible other 7.3 
> incompatibilities now and in the future changes.

Ah, thank you for the explanation. I'm not familiar with Travis.

> Unfortunately tests fails 
> <https://travis-ci.org/cakephp/acl/builds/468186115> because CakePHP 3.7 
> deprecations, so somebody needs to fix that in another PR.

CakePHP offers solutions for at least some of them. I can try later to 
fix them.


Christoph

**Comment by garas** [comment]
I've fixed deprecations in https://github.com/cakephp/acl/pull/151.

https://github.com/cakephp/acl/pull/151 should be merged first, after that your PR will be re-tested without deprecation warnings.

**Comment by garas** [comment]
7.3 tests currently fails because Xdebug is not available on PHP 7.3.

Update one more line in `.travis.yml` like in https://github.com/cakephp/bake/blob/7ff3b8df337b16d67d9834e6b438d06d9d4974ca/.travis.yml#L36

**Comment by chtheis** [comment]
Am 15.12.2018 um 13:51 schrieb Edgaras Janušauskas:
> 7.3 tests currently fails because Xdebug is not available on PHP 7.3.
> 
> Update one more line in |.travis.yml| like in 
> https://github.com/cakephp/bake/blob/7ff3b8df337b16d67d9834e6b438d06d9d4974ca/.travis.yml#L36

Done. Though I don't know what I did ;)


Christoph

**Comment by garas** [comment]
Tests now passes.

Thank you for your PR.

**Pull request merged**
