### PR TITLE
Adjust usage of deprecated methods

### LINKED ISSUE #142: On Cakephp 3.6, Acl generating deprecation warning
We are on cakephp 3.6, when we tried to view permissions node via 
`bin/cake acl view aro` , 
we have deprecation warnings.

acl warning

### PR DESCRIPTION
**Pull request by rchavik**
Closes #142

### CODE REVIEW

**Comment by rchavik** [comment]
Do we need to bump `cakephp/cakephp` version dependency to `^3.6` ?

**Comment by saeideng** [comment]
>Do we need to bump cakephp/cakephp version dependency to ^3.6 ?

no works on 3.5 
https://travis-ci.org/cakephp/acl/jobs/370876838

**Comment by ceeram** [comment]
Sorry, missed these ones. LGTM 👍

**Comment by markstory** [comment]
> Do we need to bump cakephp/cakephp version dependency to ^3.6 ?

Only if the new methods don't exist in 3.5

**Comment by piotrpoz** [comment]
Any progress on this one?

**Pull request merged**
