### PR TITLE
Add prefix support

### PR DESCRIPTION
**Pull request by Xety**

### CODE REVIEW

**Comment by markstory** [comment]
Looks reasonable to me.

**Comment by Xety** [comment]
There is still need to fix the InitDb cmd, but i will do it in another PR. (And with some help :smile:)

**Comment by rchavik** [comment]
Question: 

In croogo 2.x, we use the following format `controllers/MyPlugin/MyController/admin_index`.
Will that still work or do we need to change to `controllers/admin/MyPlugin/MyController/index` ?

**Comment by Xety** [comment]
If you don't use a prefix, yes it will still work, else no.

**Comment by markstory** [comment]
@rchavik You'll have to move all your controller actions around as well when upgrading.

**Comment by ceeram** [comment]
While all acos need to be changed anyways, could we perhaps drop the Inflector::camelize() calls in action() as well? I think that might help performance when doing many permission lookups?

**Comment by rchavik** [comment]
Is it possible to make it BC with cake2 style aros/acos records? Croogo uses route prefix, and as far as I remember, it does not do anything special with the path to make it work.

Secondly, won't this result in an extra ACO record for `MyPlugin`. Using your example, one with parent = `admin`, another with parent `controllers`.

Thirdly, getting a list of actions from a controller needs to be a two step commands:

```
$ Console/cake acl view aco controllers/MyPlugin/MyControllers
$ Console/cake acl view aco controllers/admin/MyPlugin/MyControllers
```

I prefer the previous behavior on this one.

**Comment by markstory** [comment]
The controllers are 'separate' now though.

**Comment by rchavik** [comment]
Yes.  I realized that during our talk yesterday.  I'd just have to figure out the best way to migrate existing aros/acos or use the class approach you mentioned yesterday.

**Pull request merged**
