### PR TITLE
Add support for running tests under 3.2

### PR DESCRIPTION
**Pull request by josegonzalez**

### CODE REVIEW

**Comment by markstory** [comment]
Very odd that tests are failing.

**Comment by josegonzalez** [comment]
Welp I tried. Thoughts on fixing that chronos issue?

**Comment by dakota** [comment]
That should fix it. Let's wait for the Travis.

**Comment by dakota** [comment]
Failing tests are due to https://github.com/cakephp/cakephp/pull/8245. Going to merge this so long.

**Pull request merged**
